const js = require('@eslint/js');
const globals = require('globals');
const pluginPromise = require('eslint-plugin-promise');

module.exports = [
	js.configs.recommended,
	{
		languageOptions: {
			ecmaVersion: 2021,
			sourceType: 'commonjs',
			globals: {
				...globals.browser,
				...globals.node,
				...globals.es2021,
			},
		},
		plugins: {
			promise: pluginPromise,
		},
			rules: {
			'no-async-promise-executor': 'off',
			'no-console': 'off',
			'no-regex-spaces': 'off',
			'no-debugger': 'off',
			'no-unused-vars': 'warn',
			'no-mixed-spaces-and-tabs': 'off',
			'no-undef': 'warn',
			'no-template-curly-in-string': 'warn',
			'consistent-return': 'warn',
			'array-callback-return': 'warn',
			eqeqeq: 'error',
			'no-alert': 'error',
			'no-caller': 'error',
			'no-eq-null': 'error',
			'no-eval': 'error',
			'no-extend-native': 'warn',
			'no-extra-bind': 'warn',
			'no-extra-label': 'warn',
			'no-floating-decimal': 'error',
			'no-implicit-coercion': 'warn',
			'no-loop-func': 'warn',
			'no-new-func': 'error',
			'no-new-wrappers': 'warn',
			'no-throw-literal': 'error',
			'prefer-promise-reject-errors': 'error',
			'for-direction': 'error',
			'getter-return': 'error',
			'no-await-in-loop': 'error',
			'no-compare-neg-zero': 'error',
			'no-catch-shadow': 'warn',
			'no-shadow-restricted-names': 'error',
			'callback-return': 'error',
			'handle-callback-err': 'error',
			'no-path-concat': 'warn',
			'prefer-arrow-callback': 'warn',
			'promise/always-return': 'error',
			'promise/catch-or-return': 'error',
			'promise/no-nesting': 'warn',
		},
	},
];
