name: "Deploy API"

on:
  workflow_call:
    inputs:
      environment:
        description: "Name of the environment to deploy"
        required: true
        type: string

permissions:
  id-token: write
  contents: read

defaults:
  run:
    shell: pwsh

jobs:
  deploy-api:
    runs-on: ubuntu-latest
    environment: ${{inputs.environment}}
    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version-file: 'package.json'

      - name: Install Firebase-tools
        run: npm i firebase-tools -g

      - name: Create env file for NodeJS app
        run: |
          cd api/functions
          New-Item -Path .env -ItemType File -Force
          'AZURE_STORAGE_ACCOUNT=${{ secrets.AZURE_STORAGE_ACCOUNT }}' | Add-Content .env
          'AZURE_STORAGE_ACCESS_KEY=${{ secrets.AZURE_STORAGE_ACCESS_KEY }}' | Add-Content .env
          'WORKFLOW_ACCESS_TOKEN=${{ secrets.WORKFLOW_ACCESS_TOKEN }}' | Add-Content .env
          'MAX_SCAN_SIZE=${{ vars.MAX_SCAN_SIZE }}' | Add-Content .env 

      - name: Deploy API to Firebase
        env:
          GOOGLE_APPLICATION_CREDENTIALS: service-account-key.json
        run: |
          cd api/functions
          # Create service account key file
          '${{ secrets.FIREBASE_SERVICE_ACCOUNT_KEY }}' | Out-File -FilePath service-account-key.json -Encoding utf8
          firebase use ${{ vars.FIREBASE_PROJECT }}
          firebase projects:list
          npm i
          # Set up cleanup policy for container images
          firebase functions:artifacts:setpolicy --confirm
          firebase deploy --only functions --force
          # Clean up service account key file
          Remove-Item service-account-key.json 
