name: "Deploy UI"

on:
  workflow_call:
    inputs:
      environment:
        description: "Name of the environment to deploy"
        required: true
        type: string

permissions:
  id-token: write
  contents: read

defaults:
  run:
    shell: pwsh

jobs:
  deploy-ui:
    runs-on: ubuntu-latest
    environment: ${{inputs.environment}}
    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version-file: 'package.json'

      - name: Install Firebase-tools
        run: npm i firebase-tools -g

      - name: Create env file for Svelte UI
        run: |
          cd ui
          touch .env
          echo API=${{ vars.API }} >> .env
          echo API2=${{ vars.API2 }} >> .env 
          echo DEPLOYMENTS_URL=${{ vars.DEPLOYMENTS_URL }} >> .env 
          echo MAX_SCAN_SIZE=${{ vars.MAX_SCAN_SIZE }} >> .env 

      - name: Deploy Svelte UI to Firebase
        env:
          GOOGLE_APPLICATION_CREDENTIALS: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_KEY }}
        run: |
          cd ui
          # Create service account key file
          echo '${{ secrets.FIREBASE_SERVICE_ACCOUNT_KEY }}' > service-account-key.json
          export GOOGLE_APPLICATION_CREDENTIALS="service-account-key.json"
          firebase use ${{ vars.FIREBASE_PROJECT }}
          firebase projects:list
          npm i
          npm run build
          firebase deploy --only hosting
          # Clean up service account key file
          rm service-account-key.json
